### PR TITLE
WR_Editcar Updated

### PR DESCRIPTION
**Pull request by nosfornos**
fixed sound IDs issues and added 8th and 9th gears

### CODE REVIEW

**Comment by Kromster80** [comment]
I'm not happy with unlimiting IDs. Should we really do it?

**Comment by nosfornos** [comment]
now my mods use 3xxxx soundbank IDs, and it's better than current version modders cannot their soundbanks they own and can be forced to use undesirable sounds others' made in high rate.

**Comment by nosfornos** [comment]
I tested soundbank ID: 2147483647, it works. but 2147483648 or more aren't supported.

**Comment by Kromster80** [comment]
Makes sense. Merged

**Comment by Kromster80** [comment]
Discarded as incomplete and non-proven

**Pull request merged**
